[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cloudinary>=1.42.2",
    "fastapi[standard]>=0.115.9",
    "motor>=3.7.0",
    "pydantic-settings>=2.8.1",
    "uvicorn>=0.34.0",
]
